version: "3.3"
services:

  python:
    build:
      context: ./python-ldap
      dockerfile: Dockerfile
    depends_on:
      - ldap
    volumes:
      - "ipython_data:/root/.ipython/profile_default"

  ldap:
    image: "osixia/openldap"
    #build:
    #  context: ./openldap
    #  dockerfile: Dockerfile
    environment:
      LDAP_LOG_LEVEL: "256"
      #LDAP_ADMIN_PASSWORD: "hunter2"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      #LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      #LDAP_TLS: "false"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "rootCA.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #KEEP_EXISTING_CONFIG: "false"
      #LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
      KEEP_EXISTING_CONFIG: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    expose:
      - "389"
      - "636"
    volumes:
      - "./certs:/tmp/certs"
      - "ldapdata:/container/service/slapd/assets/config/bootstrap/ldif/custom"

volumes:
  ldapdata:
  ipython_data: # To keep our iPyhon history
